### ISSUE TITLE
Got this errors lately when updating something on WP

### ISSUE THREAD

**Issue by highacid** [shield-9/opcache-dashboard#15]
Detail: array ( 'action' => 'install', 'type' => 'plugin', 'bulk' => true, 'plugins' => array ( 0 => 'http://dubfromtheground.com/wp-content/themes/music-band/framework/admin/inc/plugins/cmsms-content-composer.zip', 1 => 'http://dubfromtheground.com/wp-content/themes/music-band/framework/admin/inc/plugins/cmsms-mega-menu.zip', 2 => 'http://dubfromtheground.com/wp-content/themes/music-band/framework/admin/inc/plugins/cmsms-contact-form-builder.zip', 3 => 'https://downloads.wordpress.org/plugin/contact-form-7.4.4.1.zip', 4 => 'http://dubfromtheground.com/wp-content/themes/music-band/framework/admin/inc/plugins/LayerSlider.zip', 5 => 'https://downloads.wordpress.org/plugin/wysija-newsletters.2.7.1.zip', 6 => 'https://downloads.wordpress.org/plugin/paypal-donations.zip', 7 => 'http://dubfromtheground.com/wp-content/themes/music-band/framework/admin/inc/plugins/revslider.zip', 8 => 'https://downloads.wordpress.org/plugin/the-eve in /home/dubfromtheground/public_html/wp-content/plugins/opcache/opcache.php on line 82

**Comment by shield-9** [comment]
This output is expected. (WP_DEBUG_DISPLAY should be set to FALSE in your wp-config.php in production environment)
