### ISSUE TITLE
Running the opcache-dashboard on multiple sites

### ISSUE THREAD

**Issue by uhlhosting** [shield-9/opcache-dashboard#16]
Hello,

I run the opcache wp plugin on multiple sites, funny is that I noticed that on one of the sites, the plugin is locked, and neither reset, or invalidate will not change the plugins values. Yet on other sites this works as designed. Any idea what could be done? Here is not working: http://atec-bb.ch and here works http://dubfromtheground.com

first site reads this values:
Hits: 4.27%
Memory: 122.04MB of 1.00GB
Keys: 648 of 130987

While second:
Hits: 61.11%
Memory: 368.10MB of 1.00GB
Keys: 4173 of 130987

Anything I do to first site, nothing changed, I restarted services, php-fpm, nginx, apache... Nothing helped.

**Comment by wrrr** [comment]
Basically, you are saying these sites are on different servers. One must be set up differently than the other. 

Are you writing the same values to opcache.ini in mods-available?

**Comment by shield-9** [comment]
Check following:
1. This plugin is not tested with Nginx.
2. Check server settings. (caching plugins, etc)
3. "network-enabled" and "enabled" is different.
