### ISSUE TITLE
Plugin adoption

### ISSUE THREAD

**Issue by wolffe** [shield-9/opcache-dashboard#19]
Hi!
I want to adopt this plugin on WordPress.org and improve it.

https://wordpress.org/plugins/opcache/

**Comment by shield-9** [comment]
Thank you for your interests! But, almost yes, I have no clear future plan at the moment.
Forking/pull requests are always welcome!

**Comment by wolffe** [comment]
Okay, no problem.

Let me know if you are interested in giving it away, I am interested.
